name: Format, Lint, Type-Check, and Test

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

env:
  NODE_VERSION: 16

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - task: 'ci:format'
            output_name: 'format_result'
          - task: 'ci:lint'
            output_name: 'lint_result'
          - task: 'ci:type-check'
            output_name: 'type_check_result'
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run ${{ matrix.task }}
        id: run-task
        continue-on-error: true
        run: |
          RESULT=$(npm run ${{ matrix.task }} 2>&1 || echo "failed")
          echo "$RESULT"
          if [ "$RESULT" = "failed" ]; then
            echo "::set-output name=${{ matrix.output_name }}::failure"
            exit 1
          else
            echo "::set-output name=${{ matrix.output_name }}::success"
          fi

  test:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run ci:test

  comment:
    runs-on: ubuntu-latest
    needs: [checks, test]
    if: github.event_name == 'pull_request'
    steps:
      - name: Check for failures
        id: check-failures
        run: |
          FAILURES=false
          if [ "${{ needs.checks.outputs.format_result }}" == "failure" ]; then
            echo "Format check failed"
            FAILURES=true
          fi
          if [ "${{ needs.checks.outputs.lint_result }}" == "failure" ]; then
            echo "Lint check failed"
            FAILURES=true
          fi
          if [ "${{ needs.checks.outputs.type_check_result }}" == "failure" ]; then
            echo "Type-check failed"
            FAILURES=true
          fi
          if [ "$FAILURES" == "true" ]; then
            echo "One or more checks failed"
            exit 1
          fi

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # Summary of Format, Lint, Type-Check, and Test Results
            | Job Name | Status | Link logs |
            | --- | --- | --- |
            | Format Check | ${{ needs.checks.outputs.format_result }} | ${{ job_logs_url('checks') }} |
            | Lint Check | ${{ needs.checks.outputs.lint_result }} | ${{ job_logs_url('checks') }} |
            | Type-Check | ${{ needs.checks.outputs.type_check_result }} | ${{ job_logs_url('checks') }} |
            | Test | ${{ needs.test.result }} | ${{ job_logs_url('test') }} |

      - name: Fail if there are failures
        if: steps.check-failures.outputs.return-code == '1'
        run: exit 1
