name: Format, Lint, Type-Check, and Test

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

env:
  NODE_VERSION: 16

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    outputs:
      format: ${{ steps.format.outcome }}
      lint: ${{ steps.lint.outcome }}
      type_check: ${{ steps.type_check.outcome }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run ci:format
        if: always()
        id: format
        run: npm run ci:format

      - name: Run ci:lint
        if: always()
        id: lint
        run: npm run ci:lint

      - name: Run ci:type-check
        if: always()
        id: type_check
        run: npm run ci:type-check

  test:
    runs-on: ubuntu-latest
    needs: checks
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        if: always()
        run: npm run ci:test

  comment:
    runs-on: ubuntu-latest
    needs: [checks, test]
    if: always()
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: vercel_url
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60

      - name: Print variables
        env:
          FORMAT: ${{ needs.checks.outputs.format }}
          LINT: ${{ needs.checks.outputs.lint }}
          TYPE_CHECK: ${{ needs.checks.outputs.type_check }}
          TEST: ${{ needs.test.result }}
          COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
          COMMIT_URL: ${{ github.event.pull_request.head.repo.html_url }}/commit/${{ github.event.pull_request.head.sha }}
        run: |
          echo ${{ env.FORMAT }}
          echo ${{ env.FORMAT == 'success' && '✅' || '❌' }}
          echo ${{ needs.test.result }}
          echo ${{ env.TEST }}
          echo ${{ env.TEST == 'success' && '✅' || '❌' }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        env:
          FORMAT: ${{ needs.checks.outputs.format }}
          LINT: ${{ needs.checks.outputs.lint }}
          TYPE_CHECK: ${{ needs.checks.outputs.type_check }}
          TEST: ${{ needs.test.result }}
          COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
          COMMIT_URL: ${{ github.event.pull_request.head.repo.html_url }}/commit/${{ github.event.pull_request.head.sha }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # Status of: ${{ github.event.pull_request.title }}

            ## Last commit:
            [${{ env.COMMIT_HASH }}](${{ env.COMMIT_URL }})

            ## Job Link:
            [Job Status](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

            ## Summary

            | Format Check | Lint Check | Type Check | Test | Vercel Deploy Link |
            | --- | --- | --- | --- | --- |
            | ${{ env.FORMAT == 'success' && '✅' || '❌' }} | ${{ env.LINT == 'success' && '✅' || '❌' }} | ${{ env.TYPE_CHECK == 'success' && '✅' || '❌' }} | ${{ env.TEST == 'success' && '✅' || '❌' }} | [🚀 URL](${{ steps.vercel_url.outputs.url }}) |
