name: Format, Lint, Type-Check, and Test

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

env:
  NODE_VERSION: 16

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run ci:format
        run: npm run ci:format

      - name: Run ci:lint
        run: npm run ci:lint

      - name: Run ci:type-check
        run: npm run ci:type-check

  test:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run ci:test

  comment:
    runs-on: ubuntu-latest
    needs: [ checks, test ]
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
      - run: echo ${{steps.waitFor200.outputs.url}}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # Summary of Format, Lint, Type-Check, and Test Results
            
            ## Job Link:
            [Run Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
            ## Summary
            
            | Job Name | Status |
            | --- | --- |
            | Format Check | ${{ needs.checks.result == 'success' && '✅' || '❌' }} |
            | Lint Check | ${{ needs.checks.result == 'success' && '✅' || '❌' }} |
            | Type-Check | ${{ needs.checks.result == 'success' && '✅' || '❌' }} |
            | Test | ${{ needs.test.result == 'success' && '✅' || '❌' }} |
