name: Release

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_run:
    workflows: ["format-and-lint"]
    types:
      - completed

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        if: github.event.pull_request.merged == true
        with:
          release-type: node
          package-name: release-please-action

  merge:
    if: github.event.pull_request.merged == true
    needs: release
    runs-on: ubuntu-latest
    run: echo "Merged release!"

  pull:
    if: github.event.pull_request.merged == false
    needs: release
    runs-on: ubuntu-latest
    run: echo "Pull main inside develop"
